### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by seven-17** [i-hossen/aaeCaptcha#1]
Hello, I run the code, and have an error showed "FileNotFoundError: [Errno 2] No such file or directory: '/home/userX/aaeCaptcha/data/librispeech/LibriSpeech/dev-clean-wav/1462-170138-0026.wav'".  I also open the data/librispeech/Librispeech, there is none file named dev-clean-wav, only have a file named dev-clean. So I have a queation about should I dowload the dataset from the liberspeech official website after run the # Download and preprocess the LibriSpeech dataset ./utils/extract_process_librispeech.sh? Because I run the ./utils/extract_process_librispeech.sh, but don't have the dev-clean-wav file. I'm looking forward to your repley.

**Comment by i-hossen** [comment]
Hi,

Please make sure that the LibreSpeech dataset is downloaded and extracted before running the code. The dataset is very large, and it will take a good amount of time to fetch it. You can also download the tarballs manually and place them in the appropriate location (e.g., data/librespeech/LibreSpeech). You should be able to run most of the programs only with the dev-clean subset. Take a look at the import_librivox.py file in the DeepSpeech/bin directory to see how the datasets are prepared for DeepSpeech training and inference. 

Also, make sure to replace "/home/userX/aaeCaptcha" with the actual path of the cloned repository.

**Comment by i-hossen** [comment]
Hi,

Please make sure that the LibreSpeech dataset has been downloaded and extracted before running the code. The dataset is very large, and it will take a good amount of time to fetch it. If you download the tarballs manually, be sure to place them in the appropriate location (e.g., data/librespeech/LibreSpeech). You should be able to run most of the programs only with the dev-clean subset. Take a look at the import_librivox.py file in the DeepSpeech/bin directory to see how the datasets are prepared for DeepSpeech training and inference. 

Also, make sure to replace "/home/userX/aaeCaptcha" with the actual path of the cloned repository.
